"""
Django settings for client project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8hf8dfxrm88u%ete8rus4+#_)5941b07x+)-6lzep6lv$q=hqc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('1', 'true', 'yes', 'on')


def _split_env_list(name, default):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]


ALLOWED_HOSTS = _split_env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0')
host_ip = os.getenv('HOST_IP', '').strip()
if host_ip and host_ip not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(host_ip)
SITE_URL = os.getenv('SITE_URL', 'http://localhost:8002')
MIDDTS_API_URL = os.getenv('MIDDTS_API_URL', 'http://localhost:8000/api')
MIDDTS_API_USERNAME = os.getenv('MIDDTS_API_USERNAME', os.getenv('MIDDTS_USERNAME', 'middts'))
MIDDTS_API_PASSWORD = os.getenv('MIDDTS_API_PASSWORD', os.getenv('MIDDTS_PASSWORD', 'middts123'))
MIDDTS_API_TIMEOUT = int(os.getenv('MIDDTS_API_TIMEOUT', '10'))
MIDDTS_API_USERNAME = os.getenv('MIDDTS_API_USERNAME', os.getenv('DJANGO_SUPERUSER_USERNAME', 'middts'))
MIDDTS_API_PASSWORD = os.getenv('MIDDTS_API_PASSWORD', os.getenv('DJANGO_SUPERUSER_PASSWORD', 'middts123'))
MIDDTS_API_TOKEN = os.getenv('MIDDTS_API_TOKEN', '')
MIDDTS_API_TIMEOUT = float(os.getenv('MIDDTS_API_TIMEOUT', '15'))
# Default CSRF trusted origins (add Codespaces domain when present)
_default_csrf = [
    'http://localhost',
    'https://localhost',
    'http://127.0.0.1',
    'https://127.0.0.1',
    'http://localhost:8002',
    'https://localhost:8002',
]

codespace_name = os.getenv('CODESPACE_NAME', '').strip()
codespaces_domain = os.getenv('GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN', '').strip()
if codespace_name and codespaces_domain:
    _default_csrf.append(f'https://{codespace_name}-8002.{codespaces_domain}')

CSRF_TRUSTED_ORIGINS = [o for o in os.getenv('CSRF_TRUSTED_ORIGINS', ','.join(_default_csrf)).split(',') if o]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ninja',
    'twins',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Ajuste a configuração de CORS para permitir comunicação com o Middts:
CORS_ALLOWED_ORIGINS = _split_env_list(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:8000,https://localhost:8000,http://127.0.0.1:8000,https://127.0.0.1:8000,http://localhost:8002,https://localhost:8002,http://127.0.0.1:8002,https://127.0.0.1:8002',
)

ROOT_URLCONF = 'client.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'client.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.getenv('SQLITE_DB_PATH', str(BASE_DIR / 'db.sqlite3')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

SESSION_COOKIE_NAME = 'sessionid_middts_client'
CSRF_COOKIE_NAME = 'csrftoken_midts_client'
