# Generated by Django 5.1.6 on 2025-02-14 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], max_length=50)),
                ('middts_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('middts_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalTwinInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('properties_json', models.JSONField(default=dict)),
                ('middts_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DTDLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specification', models.JSONField()),
                ('dtmi', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('middts_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('middts_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=255)),
                ('middts_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='twins.device')),
            ],
            options={
                'unique_together': {('device', 'name')},
            },
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='twins.devicetype'),
        ),
        migrations.CreateModel(
            name='DigitalTwinProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middts_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('causal', models.BooleanField(default=False)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='twins.digitaltwininstance')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalTwinDevicePropertyBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_mapping', models.JSONField()),
                ('device_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twins.deviceproperty')),
                ('dt_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twins.digitaltwinproperty')),
            ],
        ),
        migrations.AddField(
            model_name='digitaltwininstance',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='twins.dtdlmodel'),
        ),
        migrations.CreateModel(
            name='ModelElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('element_type', models.CharField(max_length=50)),
                ('data_type', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='twins.dtdlmodel')),
                ('target_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_elements', to='twins.dtdlmodel')),
            ],
            options={
                'unique_together': {('model', 'name', 'element_type')},
            },
        ),
        migrations.AddField(
            model_name='dtdlmodel',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtdl_models', to='twins.systemcontext'),
        ),
        migrations.CreateModel(
            name='DigitalTwinInstanceRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=255)),
                ('source_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relationships', to='twins.digitaltwininstance')),
                ('target_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relationships', to='twins.digitaltwininstance')),
            ],
            options={
                'unique_together': {('source_instance', 'target_instance', 'relationship')},
            },
        ),
        migrations.CreateModel(
            name='ModelRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_dtmi', models.CharField(max_length=255)),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='twins.modelelement')),
                ('source_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='twins.dtdlmodel')),
                ('target_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='twins.dtdlmodel')),
            ],
            options={
                'unique_together': {('source_model', 'target_model', 'name')},
            },
        ),
    ]
