# Generated by Django 5.1.6 on 2025-02-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twins', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='digitaltwindevicepropertybinding',
            unique_together={('dt_property', 'device_property')},
        ),
        migrations.RemoveField(
            model_name='digitaltwindevicepropertybinding',
            name='property_mapping',
        ),
    ]
