# Generated by Django 5.1.6 on 2025-02-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaltwininstance',
            name='middts_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dtdlmodel',
            name='middts_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='systemcontext',
            name='middts_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
