# Generated by Django 5.1.6 on 2025-02-11 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twins', '0002_digitaltwininstance_middts_id_dtdlmodel_middts_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalTwinInstanceRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=255)),
                ('source_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relationships', to='twins.digitaltwininstance')),
                ('target_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relationships', to='twins.digitaltwininstance')),
            ],
            options={
                'unique_together': {('source_instance', 'target_instance', 'relationship')},
            },
        ),
    ]
