# Generated by Django 5.1.6 on 2025-02-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twins', '0002_alter_digitaltwindevicepropertybinding_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dtdlmodel',
            name='middts_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dtdlmodel',
            unique_together={('system', 'middts_id')},
        ),
    ]
