# Generated by Django 5.1.6 on 2025-02-11 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twins', '0003_digitaltwininstancerelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('element_type', models.CharField(max_length=50)),
                ('data_type', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='twins.dtdlmodel')),
                ('target_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_elements', to='twins.dtdlmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ModelRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_model_name', models.CharField(max_length=255)),
                ('source_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='twins.dtdlmodel')),
                ('target_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='twins.dtdlmodel')),
            ],
        ),
    ]
