# Generated by Django 5.1.6 on 2025-02-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twins', '0003_alter_device_status_alter_dtdlmodel_middts_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dtdlmodel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dtdlmodel',
            name='dtmi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dtdlmodel',
            name='middts_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='dtdlmodel',
            unique_together={('system', 'middts_id', 'dtmi')},
        ),
    ]
