# Generated by Django 5.1.6 on 2025-02-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twins', '0004_alter_dtdlmodel_unique_together_alter_dtdlmodel_dtmi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaltwininstancerelationship',
            name='middts_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='modelrelationship',
            name='middts_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
