# Generated by Django 5.1.6 on 2025-02-11 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twins', '0004_modelelement_modelrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrelationship',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='twins.modelelement'),
        ),
        migrations.AlterUniqueTogether(
            name='modelelement',
            unique_together={('model', 'name', 'element_type')},
        ),
        migrations.AlterUniqueTogether(
            name='modelrelationship',
            unique_together={('source_model', 'target_model', 'name')},
        ),
    ]
