# Generated by Django 5.1.6 on 2025-02-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twins', '0005_modelrelationship_element_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelrelationship',
            old_name='target_model_name',
            new_name='target_dtmi',
        ),
        migrations.AddField(
            model_name='dtdlmodel',
            name='dtmi',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
