# Generated by Django 5.1.6 on 2025-02-11 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twins', '0006_rename_target_model_name_modelrelationship_target_dtmi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitaltwininstance',
            old_name='properties',
            new_name='properties_json',
        ),
        migrations.CreateModel(
            name='DigitalTwinProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('causal', models.BooleanField(default=False)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='twins.digitaltwininstance')),
            ],
        ),
    ]
