# Generated by Django 5.1.6 on 2025-02-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twins', '0007_rename_properties_digitaltwininstance_properties_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaltwinproperty',
            name='middts_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
