# Generated by Django 5.1.6 on 2025-02-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twins', '0008_digitaltwinproperty_middts_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaltwinproperty',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
